### ISSUE TITLE
FAILED, aborting any pending transactions

### ISSUE THREAD

**Issue by erenozm** [litehelpers/Cordova-sqlcipher-adapter#44]
everything was working fine. i don't know what happened but i am getting this error when i am trying to run the app 2nd time after installation.

```
OPEN database: db.db
OPEN database: db.db FAILED, aborting any pending transactions
Could not open database
TypeError: undefined is not a function
    at SQLitePlugin.transaction (file:///android_asset/www/plugins/cordova-sqlcipher-adapter/www/SQLitePlugin.js:115:7)
    at Object.execute (file:///android_asset/www/js/ng-cordova.min.js:9:23737)
    at Scope.$scope.searchWord (file:///android_asset/www/js/controllers.js:411:17)
    at fn (eval at <anonymous> (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:27643:15), <anonymous>:4:294)
    at Scope.$eval (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30400:28)
    at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:37225:13
    at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:39989:9
    at forEach (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:13696:20)
    at $$writeModelToScope (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:39987:5)
    at writeToModelIfNeeded (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:39980:14)

```

any help is much appreciated.

**Comment by erenozm** [comment]
i fixed the problem it was my fault. i tried to delete the issue but i guess it is not possible.
